name: Selenium Tests

on: [push, pull_request]

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Specify the JDK distribution

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run tests
      run: mvn test
      env:
        DISPLAY: ':99.0'
